name: stacked_card_carousel
description: Animated carousel widget with stacked cards.
version: 0.0.1
author: Grigori Hlopkov
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
