name: stacked_card_carousel
description: A widget for creating a vertical carousel with stacked cards.
version: 0.0.1
author: Grigori Hlopkov
homepage: https://github.com/grihlo/stacked_card_carousel

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
